### ISSUE TITLE
歌词页进度条显示错误

### ISSUE THREAD

**Issue by pop-tianlang** [BetterNCM/FluentProgessBar#3]
在歌词页中左侧进度条会直接推到头

**Comment by std-microblock** [comment]
![image](https://user-images.githubusercontent.com/66859419/212458318-39eaff72-8c83-4d2c-82c1-a05f9d7b3569.png)
请关闭如图所示选项

**Comment by ybhgl** [comment]
> ![image](https://user-images.githubusercontent.com/66859419/212458318-39eaff72-8c83-4d2c-82c1-a05f9d7b3569.png) 请关闭如图所示选项

已经关闭该选项，还是会有错位情况，进度条的开头飞了，结尾正常
![Snipaste_2023-01-18_17-02-09](https://user-images.githubusercontent.com/35188529/213129188-7e5db4a4-d4d0-40bd-b4f5-1b3b279674a9.png)
![Snipaste_2023-01-18_17-03-50](https://user-images.githubusercontent.com/35188529/213129205-3c468498-d4cb-4996-be4c-d4cd98e4ef12.png)

**Comment by std-microblock** [comment]
![image](https://user-images.githubusercontent.com/66859419/213131209-3f3ca1c0-2f91-4f24-b01b-54032ab0a941.png)
关闭后应该长这样

**Comment by cow-your-sister** [comment]
【实测有效】这个选项默认是关闭的，作者说的关闭就是把按钮弄到关闭状态。但是由于它默认关闭，所以需要点开手动开关一遍（最好多试几遍），然后重载BetterNCM
