### ISSUE TITLE
进度条错位啦

### ISSUE THREAD

**Issue by NODT4109** [BetterNCM/FluentProgessBar#4]
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/109859658/214562473-483daaa1-902c-4b5e-ac97-8458eafc8d7b.png">
进度条不知道为什么就变成这个样子了

**Comment by NODT4109** [comment]
好像是更新material you后出现的 已经去material you下面反映了相同的问题了

**Comment by std-microblock** [comment]
#3
