### ISSUE TITLE
开始播放后进度条尾部显示错误

### ISSUE THREAD

**Issue by Nekonyann** [BetterNCM/FluentProgessBar#6]
### 环境:
BetterNCM 1.0.1
FluentProgessBar 0.2.0
网易云 2.10.5(Build:200451),2.10.6(Build 200601)(Patch:1:5ad43a6)

### 截图:
![image](https://user-images.githubusercontent.com/42025222/217733116-3725f0fb-e889-456b-86e1-03e1ce669d0d.png)
![image](https://user-images.githubusercontent.com/42025222/217734227-df233604-5273-4bc1-bf8d-be02144f4a66.png)
![image](https://user-images.githubusercontent.com/42025222/217990573-6231cc70-90df-45f9-bf64-b5fc6a19ff76.png)

### 补充:
使用网易云内置主题下两个网易云版本均出现此问题
配合Material You使用或卸载插件后进度条显示正常

**Comment by ZacharyBacon** [comment]
这个是主题的问题吧，你看下这 https://github.com/solstice23/material-you-theme-netease/issues/34#issue-1574432712

**Comment by weijinzhongyi** [comment]
我在用默认皮肤的时候也有这个问题,一模一样,都是最新版的插件

**Comment by std-microblock** [comment]
#7 duplicated
