### ISSUE TITLE
进度有问题，怎么前面有一大截出来了啊？？

### ISSUE THREAD

**Issue by as514420203** [BetterNCM/FluentProgessBar#7]
![image](https://user-images.githubusercontent.com/128178413/225984818-ced6e378-c65d-4477-89d2-9913a9867509.png)

**Comment by as514420203** [comment]
![image](https://user-images.githubusercontent.com/128178413/225987284-a1faca5c-2a32-4fb1-8d15-5b53555bbd16.png)进度是不知道为什么我的就是这样，看着太难受了

**Comment by std-microblock** [comment]
#3
